version: "3.3"
services:
  vk:
    build:
        context: .
        args:
            VERSION: vk
    environment:
      - VK_TOKEN
      - VK_SECRET_KEY
      - VK_GROUP_ID
      - VK_CONFIRMATION_STRING

    ports:
      - "127.0.0.1:8888:8000"
    restart: "always"
  telegram:
      build:
          context: .
          args:
              VERSION: telegram
      environment:
        - TG_TOKEN
      restart: "always"
  redis:
    image: "redis:6.0.9"
    restart: "always"
